# syntax=docker/dockerfile:1

FROM node:22-alpine AS base

RUN apk add --no-cache libc6-compat openssl

WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1

##########################################

FROM base AS deps

COPY package*.json ./

RUN npm ci

##########################################

FROM base AS builder

COPY --from=deps /app/node_modules ./node_modules

COPY . .

ENV DATABASE_URL="postgresql://build:build@localhost:5432/build"

RUN npx prisma generate

RUN npm run build

##########################################

FROM base AS migrator

COPY --from=deps /app/node_modules ./node_modules

COPY prisma ./prisma
COPY prisma.config.ts ./
COPY package.json ./

ENV DATABASE_URL="postgresql://build:build@localhost:5432/build"

RUN npx prisma generate

##########################################

FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV HOSTNAME=0.0.0.0
ENV PORT=5000

RUN apk add --no-cache libc6-compat openssl

RUN addgroup -S nodejs \
 && adduser -S nextjs -G nodejs

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

COPY --from=builder --chown=nextjs:nodejs /app/public ./public

RUN mkdir -p /app/uploads

USER nextjs

EXPOSE 5000

CMD ["node", "server.js"]